### ISSUE TITLE
Using Spine 3.8

### ISSUE THREAD

**Issue by cherish-ltt** [jabuwu/bevy_spine#25]
How to use the old version of spineV3.8？
Learning Spine 4.2 is very difficult

**Comment by jabuwu** [comment]
Sorry, but this crate only supports the latest Spine runtime. As far as I understand it, Spine 4.2 is not any more difficult to learn than 3.8, and upgrading old project files is simple. It's significantly less work to upgrade the files than to add support for 3.8 in this crate.

It's not the first time I've received this request. There's an outdated PR that added support for this in the runtime library (https://github.com/jabuwu/rusty_spine/pull/3), but I personally don't have time to maintain two versions.
