### ISSUE TITLE
Can I configure the image filters (eg min_filter) somehow?

### ISSUE THREAD

**Issue by Droggelbecher** [jabuwu/bevy_spine#26]
I'm looking to set the spine textures min filter, currently it seems to be set to nearest which looks undesirable when zooming out.
Internally there seems to be a SpineTextureConfig struct with that information that is used eg. in events but I couldn't find a way for a user of bevy_spine to  configure it (instead it seems it gets its configuration from rusty spine?).

Would be grateful for any advice :)

**Comment by jabuwu** [comment]
When exporting from Spine, in "Pack Settings," `bevy_spine` should honor the runtime values specified here:

<img width="306" alt="Screenshot 2024-11-10 at 5 21 55 AM" src="https://github.com/user-attachments/assets/da4d90c0-f303-4ef2-9b33-72b17c064e42">

Changing the value at runtime would be harder but should also be possible. Let me know if this is enough for you.

**Comment by Droggelbecher** [comment]
Thanks for the quick reply, indeed I wasnt aware of these settings :-) First impression is it doesn't seem to actually solve my issue but perhaps what I actually want/need is TAA (as I have no reasonable complaints about any given still frame but zoomed out the animation just doesnt look nice due to aliasing type artefacts) which would be out of scope of bevy_spine. Thanks again for the quick help!
